force-app/main/default/objects/Solar_Farm__c/Solar_Farm__c.object-meta.xml
<CustomObject>
    <label>Solar Farm</label>
    <nameField>
        <label>Solar Farm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solar Farms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Solar_Farm__c.field-meta.xml
<CustomField>
    <fullName>Solar_Farm__c</fullName>
    <label>Solar Farm</label>
    <referenceTo>Solar_Farm__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubscriptionSelector.cls
/**
 * Created by brooks on 10/21/2022.
 */

public with sharing class SubscriptionSelector {

    public  List<Subscription__c> getExistingSubscriptionsByCustomerAndFarmId(Set<Id> customerIds, Set<Id> solarFarmIds) {
        return [SELECT Id, Expiration_Date__c, Start_Date__c, Customer__c
        FROM Subscription__c
                WHERE Customer__c IN: customerIds
                AND Solar_Farm__c IN: solarFarmIds
        ];
    }

}